title: Liora Milbaum's blog
author: Liora Milbaum
email: liora@lmb.co.il
url: lioramilbaum.github.io
description: "Liora Milbaum's blog"
remote_theme: huangyz0918/moving

moving:
  social_links:
      github:  lioramilbaum
      facebook: liora.milbaum
      linkedin: lioramilbaum